apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: view-events-binding
  namespace: nsm-dev
subjects:
- kind: ServiceAccount
  name: default
  namespace: nsm-dev
roleRef:
  kind: Role
  name: view-events
  apiGroup: rbac.authorization.k8s.io
