[package]
name = "heartbeat_monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
threadpool = "1.8"

[[bin]]
name = "heartbeats"
path = "src/heartbeats.rs"

[[bin]]
name = "listener"
path = "src/listener.rs"